(require 'ert)
(require 'imgix)
(require 'ht)

(ert-deftest imgix-build-qs-test ()
  (let* ((qs (ht-create)))
    (ht-set! qs "w" "500")
    (ht-set! qs "h" "700")
    (should (string= (imgix-build-qs qs)
                     "w=500&h=700"))))

(imgix-build-qs-test)
  ;; (let ((test-table (ht (1 2) ("foo" (1+ 2)))))
  ;;   (should (and (member 1 (ht-keys test-table))
  ;;                (member "foo" (ht-keys test-table))
  ;;                (member 2 (ht-values test-table))
  ;;                (member 3 (ht-values test-table))))))
